#
# This program and the accompanying materials are made available under the terms of the
# Eclipse Public License v2.0 which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-v20.html
#
# SPDX-License-Identifier: EPL-2.0
#
# Copyright IBM Corporation 2018
#

spring:
    application:
        name: data-sets
    output:
        ansi:
            enabled: detect

logging:
    level:
        ROOT: INFO
        org.springframework: INFO
        org.zowe: DEBUG

apiml:
    security:
        ssl:
            ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384

server:
  port: ${server.port}
  ssl:
    keyStore: ${server.ssl.keyStore}
    keyStorePassword: ${server.ssl.keyStorePassword}
    keyStoreType: ${server.ssl.keyStoreType}
    keyAlias: ${server.ssl.keyAlias}
    enabled-protocols: TLSv1.2
    ciphers: ${apiml.security.ssl.ciphers}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css  
    
zosmf:
  ipAddress: ${zosmf.ipAddress}
  httpsPort: ${zosmf.httpsPort}

logbackServiceName: ZWEEAD1
